name: Test

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflow/test.yml'
      - 'package.json'
      - 'index.js'
      - 'common.js'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci
    - name: npm run test
      run: npm run test
